import type { ConstitutionScores, ConstitutionType } from "@qiorazen/types";
import type { TongueAnalysisResult } from "@qiorazen/types";
import { WELLNESS_INSIGHT_SYSTEM_PROMPT, TONGUE_ANALYSIS_PROMPT, buildUserMessage } from "./prompts";
import { sanitizeOutput } from "./guardrails";
import { detectSeriousSymptoms } from "./symptom-detector";

export interface WellnessInsightInput {
  constitutionScores: ConstitutionScores;
  primaryConstitution: ConstitutionType;
  userQuestions: string[];
  tongueAnalysis?: TongueAnalysisResult;
  language: "en" | "zh";
}

export interface WellnessInsightOutput {
  constitutionSummary: string;
  wellnessInsights: string;
  lifestyleSuggestions: {
    dietary_tendencies: string[];
    activity_suggestions: string[];
    lifestyle_habits: string[];
  };
  seriousFlag: boolean;
  violations: string[];
  mock: boolean;
}

/**
 * Generate a wellness insight using Claude API.
 * Falls back to mock response if ANTHROPIC_API_KEY is not set.
 */
export async function generateWellnessInsight(
  input: WellnessInsightInput
): Promise<WellnessInsightOutput> {
  // Pre-check: serious symptoms
  const symptomCheck = detectSeriousSymptoms(input.userQuestions);
  if (symptomCheck.detected) {
    return {
      constitutionSummary: "",
      wellnessInsights: "",
      lifestyleSuggestions: { dietary_tendencies: [], activity_suggestions: [], lifestyle_habits: [] },
      seriousFlag: true,
      violations: [],
      mock: false,
    };
  }

  // If no API key, return mock response
  if (!process.env.ANTHROPIC_API_KEY) {
    return generateMockResponse(input);
  }

  // Real API call
  const { default: Anthropic } = await import("@anthropic-ai/sdk");
  const anthropic = new Anthropic();

  const response = await anthropic.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 2000,
    system: WELLNESS_INSIGHT_SYSTEM_PROMPT,
    messages: [{ role: "user", content: buildUserMessage({
      ...input,
      tongueAnalysis: input.tongueAnalysis as unknown as Record<string, unknown> | undefined,
    }) }],
  });

  const rawText = response.content[0].type === "text" ? response.content[0].text : "{}";

  let parsed;
  try {
    parsed = JSON.parse(rawText);
  } catch {
    parsed = {
      constitution_summary: rawText,
      wellness_insights: rawText,
      lifestyle_suggestions: { dietary_tendencies: [], activity_suggestions: [], lifestyle_habits: [] },
      serious_flag: false,
    };
  }

  // Sanitize through guardrails
  const sanitizedSummary = sanitizeOutput(parsed.constitution_summary ?? "");
  const sanitizedInsights = sanitizeOutput(parsed.wellness_insights ?? "");

  const allViolations = [
    ...sanitizedSummary.violations,
    ...sanitizedInsights.violations,
  ];

  return {
    constitutionSummary: sanitizedSummary.sanitizedText,
    wellnessInsights: sanitizedInsights.sanitizedText,
    lifestyleSuggestions: parsed.lifestyle_suggestions ?? {
      dietary_tendencies: [],
      activity_suggestions: [],
      lifestyle_habits: [],
    },
    seriousFlag: parsed.serious_flag ?? false,
    violations: allViolations,
    mock: false,
  };
}

/**
 * Mock response for development without API key.
 */
function generateMockResponse(input: WellnessInsightInput): WellnessInsightOutput {
  const isZh = input.language === "zh";

  return {
    constitutionSummary: isZh
      ? `根据您的体质测评结果，您的主要体质倾向为${input.primaryConstitution}。这种体质模式在传统养生文献中有丰富的描述，代表了一种特定的身体倾向和生活方式偏好。`
      : `Based on your wellness screening, your primary constitutional tendency is ${input.primaryConstitution}. This pattern is well-documented in traditional wellness literature and represents a specific set of physical tendencies and lifestyle preferences.`,
    wellnessInsights: isZh
      ? `[模拟回复] 这是基于您的体质类型和提出的问题生成的模拟养生建议。正式上线后，此内容将由 AI 根据您的具体情况个性化生成，并经过养生顾问审核确认。\n\n您的问题：\n${input.userQuestions.map((q, i) => `${i + 1}. ${q}`).join("\n")}\n\n本信息仅供教育参考，不构成医疗建议。`
      : `[Mock Response] This is a simulated wellness insight based on your constitution type and questions. In production, this content will be personally generated by AI based on your specific situation and reviewed by a wellness advisor.\n\nYour questions:\n${input.userQuestions.map((q, i) => `${i + 1}. ${q}`).join("\n")}\n\nThis information is for educational purposes only and is not medical advice.`,
    lifestyleSuggestions: {
      dietary_tendencies: isZh
        ? ["温热易消化的食物可能更适合您的体质", "按时进餐，避免过饱", "多喝温水"]
        : ["Warm, easily digestible foods may suit your constitution", "Regular meal times, avoid overeating", "Stay hydrated with warm water"],
      activity_suggestions: isZh
        ? ["适度运动如散步、太极", "避免过度劳累", "运动后注意保暖"]
        : ["Moderate exercise like walking or tai chi", "Avoid overexertion", "Stay warm after exercise"],
      lifestyle_habits: isZh
        ? ["早睡早起，23点前入睡", "保持情绪平和", "注意保暖"]
        : ["Sleep before 11pm, rise early", "Maintain emotional balance", "Keep warm"],
    },
    seriousFlag: false,
    violations: [],
    mock: true,
  };
}

/**
 * Analyze a tongue image using Claude Vision.
 * Falls back to mock if no API key.
 */
export async function analyzeTongueImage(
  imageBase64: string,
  mimeType: string = "image/jpeg"
): Promise<{ analysis: TongueAnalysisResult; observations: string; mock: boolean }> {
  if (!process.env.ANTHROPIC_API_KEY) {
    return {
      analysis: {
        tongue_color: "light_pink",
        coating: "thin_white",
        shape: "normal",
        features: ["teeth_marks"],
      },
      observations: "[Mock] In traditional tongue reading literature, this appearance is commonly described as within the normal range. This is an educational observation, not a medical assessment.",
      mock: true,
    };
  }

  const { default: Anthropic } = await import("@anthropic-ai/sdk");
  const anthropic = new Anthropic();

  const response = await anthropic.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 1000,
    messages: [{
      role: "user",
      content: [
        {
          type: "image",
          source: { type: "base64", media_type: mimeType as "image/jpeg", data: imageBase64 },
        },
        { type: "text", text: TONGUE_ANALYSIS_PROMPT },
      ],
    }],
  });

  const rawText = response.content[0].type === "text" ? response.content[0].text : "{}";
  let parsed;
  try {
    parsed = JSON.parse(rawText);
  } catch {
    parsed = { tongue_color: "pink", coating: "thin_white", shape: "normal", features: [], observations: rawText };
  }

  const sanitized = sanitizeOutput(parsed.observations ?? "");

  return {
    analysis: {
      tongue_color: parsed.tongue_color ?? "pink",
      coating: parsed.coating ?? "thin_white",
      shape: parsed.shape ?? "normal",
      features: parsed.features ?? [],
    },
    observations: sanitized.sanitizedText,
    mock: false,
  };
}
